from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path


SHARED = Path(__file__).parents[1]
SCRIPT = SHARED / "scripts" / "audit_manuscript_surface.py"

spec = importlib.util.spec_from_file_location("audit_manuscript_surface", SCRIPT)
assert spec and spec.loader
mod = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = mod
spec.loader.exec_module(mod)


def kinds(text: str) -> set[str]:
    return {f.kind for f in mod.audit_text(text)}


class ManuscriptSurfaceQATests(unittest.TestCase):
    def test_flags_repository_and_code_residue(self) -> None:
        text = """## Results
Panel b was generated by scripts/plot_auc.py using `compute_site_auc()` and --fold-id.
See PR #41 and commit deadbeef for the final version.
"""
        found = kinds(text)
        self.assertIn("repository_path", found)
        self.assertIn("code_identifier", found)
        self.assertIn("cli_flag", found)
        self.assertIn("developer_history", found)

    def test_flags_standalone_code_filename(self) -> None:
        found = kinds("The analysis used preprocess.py before model fitting.")
        self.assertIn("code_filename", found)

    def test_flags_local_path_and_output_filename(self) -> None:
        found = kinds("The image was exported to /Users/me/project/fig2_final_v7.svg.")
        self.assertIn("local_path", found)
        self.assertIn("output_filename", found)

    def test_flags_normal_windows_path(self) -> None:
        findings = mod.audit_text(r"The file was read from C:\Users\me\project\results.csv.")
        self.assertTrue(any(f.kind == "local_path" and f.severity == "error" for f in findings))

    def test_scientific_slash_phrases_are_not_repository_errors(self) -> None:
        text = "The test/retest reliability is reported in the Results/Discussion transition, with output/input ratios summarized separately."
        findings = mod.audit_text(text)
        self.assertFalse(any(f.kind == "repository_path" and f.severity == "error" for f in findings))

    def test_deep_extensionless_project_like_path_is_review_only(self) -> None:
        findings = mod.audit_text("See results/experiment_a/run_03 for the internal record.")
        matches = [f for f in findings if f.kind == "repository_path_review"]
        self.assertEqual(len(matches), 1)
        self.assertEqual(matches[0].severity, "review")

    def test_repository_url_is_reviewed_and_availability_context_recorded(self) -> None:
        body = mod.audit_text("Results are available at https://github.com/example/project.")
        self.assertTrue(any(f.kind == "repository_url" and not f.availability_context for f in body))
        availability = mod.audit_text("## Code Availability\nhttps://github.com/example/project\n")
        self.assertTrue(any(f.kind == "repository_url" and f.availability_context for f in availability))

    def test_mechanical_punctuation_is_flagged(self) -> None:
        found = kinds("This is wrong ,,and Fig.. 2 is broken .")
        self.assertIn("repeated_punctuation", found)
        self.assertIn("space_before_punctuation", found)
        self.assertIn("figure_reference_punctuation", found)

    def test_numeric_range_is_review_not_error(self) -> None:
        findings = mod.audit_text("Samples were incubated for 5-10 min.")
        matches = [f for f in findings if f.kind == "range_hyphen_review"]
        self.assertEqual(len(matches), 1)
        self.assertEqual(matches[0].severity, "review")

    def test_normal_scientific_prose_is_not_treated_as_code(self) -> None:
        text = "Site-level discrimination was evaluated across three external cohorts (n = 418)."
        found = kinds(text)
        self.assertNotIn("code_filename", found)
        self.assertNotIn("repository_path", found)
        self.assertNotIn("code_identifier", found)

    def test_accession_and_doi_are_not_flagged_as_code_files(self) -> None:
        text = "Data are deposited under accession GSE123456 and DOI 10.5281/zenodo.1234567."
        found = kinds(text)
        self.assertNotIn("code_filename", found)

    def test_unbalanced_delimiters_are_flagged(self) -> None:
        found = kinds("The estimate (95% CI [0.10, 0.20].")
        self.assertIn("unbalanced_parentheses", found)

    def test_unbalanced_delimiters_inside_fenced_code_do_not_fail_prose(self) -> None:
        text = """The prose is balanced (and complete).
```python
x = func([1, 2
```
The manuscript continues normally.
"""
        findings = mod.audit_text(text)
        self.assertFalse(any(f.kind.startswith("unbalanced_") for f in findings))
        self.assertTrue(any(f.kind == "code_fence" for f in findings))


if __name__ == "__main__":
    unittest.main()
